apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "jupyter-notebook.fullname" . }}-nginx-configmap
  labels:
    app.kubernetes.io/name: {{ include "jupyter-notebook.name" . }}
    helm.sh/chart: {{ include "jupyter-notebook.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
data:
  nginx.conf: |
    # nginx.conf
    pid /tmp/nginx.pid;
    events {
        worker_connections  1024;
    }

    http {
        proxy_buffering off;
        proxy_http_version 1.1;
        proxy_set_header Proxy "";        
        proxy_set_header Host $http_host;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Uri /{{ .Values.jupyter.config.baseUrl }};

        server {
            listen {{ .Values.nginx.port }};
            server_name {{ .Values.nginx.portName }};
            port_in_redirect off;
            root   /usr/share/nginx/html;
            index  index.html index.htm;
            include /etc/nginx/mime.types;

            access_log /var/log/nginx/access.log;
            error_log  /var/log/nginx/error.log;

            location /{{ .Values.jupyter.config.baseUrl }} {
              proxy_pass http://127.0.0.1:{{ .Values.jupyter.port }};
            }
        }
    }