apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "jupyter-notebook.fullname" . }}-networkpolicy
spec:
  ingress:
  - ports:
    - port: {{ .Values.service.targetPort }}
      protocol: TCP
  podSelector:
    matchLabels:
      app.kubernetes.io/name: {{ include "jupyter-notebook.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
